import Head from 'next/head'
import { useSession } from "next-auth/react"
import { useRouter } from 'next/router'
import { useEffect } from 'react';
import { CircularProgress } from '@mui/material';
import { STUDENT_DOMAIN_NAME, TEACHER_DOMAIN_NAME } from '@/utils/emailDomainName';

export default function Home() {
  // hook
  const { data: session } = useSession(null);
  const router = useRouter()
  useEffect(() => {
    if (session) {
      const email = session?.user?.email

      if (email.endsWith(STUDENT_DOMAIN_NAME)) {
        router.push("/Home")
      }
      else if (email.endsWith(TEACHER_DOMAIN_NAME)) {
        router.push("Home")
    }
      else{
        router.push("/login")
      }
      
    } else {
      router.push("/login")
    }
  }, [router, session])
  return (
    <>
      <Head>
        <title>SA Systems</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main>
        <style jsx>{`
        .container {
          width: 100vw;
          height: 100vh;
          background-color: #EEF2F6;
          display: flex;
          align-items: center;
          justify-content: center;
      }
      `}</style>
        <div className="container">
          <CircularProgress color="primary" />
        </div>
      </main>
    </>
  )
}
